#!/bin/bash

function check() {
  if [ $? -eq 0 ]; then
    echo Step Complete
  else
    echo Step Failed
    exit
  fi
}

sudo apt-get update

sudo apt-get install \
  fish \
  tmux \
  python3 \
  python3-pip \
  neovim \
  silversearcher-ag \
  jq \
  perl \
  clang \
  make \
  less \
  gawk \
  htop \
  curl

check

sudo chown -R $USER:$USER /usr/local

curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
check

sudo apt-get install -y nodejs
check

pip install awscli neovim awslogs httpie
check

sudo npm i -g nodemon fx cwl jay-repl eslint eslint-config-firstandthird eslint-plugin-import
check

TF_VERSION=0.12.7
##wget --quiet https://releases.hashicorp.com/terraform/$TF_VERSION/terraform_$TF_VERSION_linux_amd64.zip \ && unzip terraform_$TF_VERSION_linux_amd64.zip \
##  && mv terraform /usr/local/bin \
##  && rm terraform_$TF_VERSION_linux_amd64.zip
##check

#docker compose
sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
check

#docker extras
curl -sSL https://raw.githubusercontent.com/jgallen23/docker-extras/master/install.sh | sudo bash
check

#git extras
curl -sSL https://raw.githubusercontent.com/tj/git-extras/master/install.sh | bash /dev/stdin
check

#linuxbrew
#/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
#check

#sam
#brew tap aws/tap
#brew install aws-sam-cli

curl -L https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install > $HOME/install && \
  chmod +x $HOME/install && \
  $HOME/install --noninteractive && \
  rm $HOME/install
check

ln -fs $PWD/vim $HOME/.vim
mkdir -p $HOME/.config/nvim
ln -fs $PWD/vim/vimrc $HOME/.config/nvim/init.vim
ln -fs $PWD/tmux.conf $HOME/.tmux.conf
ln -fs $PWD/gitconfig $HOME/.gitconfig
ln -fs $PWD/npmrc $HOME/.npmrc
rm -rf $HOME/.config/fish
ln -fs $PWD/fish $HOME/.config/fish
#ln -fs $PWD/eslintrc $HOME/.eslintrc

mkdir -p $HOME/.vim/bundle
if [[ ! -d "$HOME/.vim/bundle/vundle" ]]; then
  git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/vundle
fi

mkdir -p $HOME/work

if [[ ! -d "$HOME/work/aws-extras" ]]; then
  git clone https://github.com/firstandthird/aws-extras.git $HOME/work/aws-extras
fi

if [[ ! -d "$HOME/work/swarm-cli" ]]; then
  git clone https://github.com/firstandthird/swarm-cli.git $HOME/work/swarm-cli
fi

nvim -es -u $HOME/.vim/bundles.vim +PluginInstall +q

#sudo chsh -s fish $USER
sudo chsh -s /usr/bin/fish $USER

#omf install aws
#omf install cbjohnson
#omf install aws-asp
#omf theme cbjohnson
