#!/usr/bin/env fish

omf install cbjohnson
omf theme cbjohnson

if test -d /ssh
  echo "updating ssh"
  rm -fr $HOME/.ssh
  sudo cp -r /ssh $HOME/.ssh
  sudo chown -R $USER:$USER $HOME/.ssh
  chmod 600 $HOME/.ssh/id_rsa*
end

sudo chown -R $USER:$USER /work/$PROFILE_NAME

if test -n $DOCKER_GROUP_ID
  groupmod -g $DOCKER_GROUP_ID docker
end
sh
