#!/usr/bin/env fish

omf install cbjohnson
omf theme cbjohnson

if test -d /ssh
  echo "updating ssh"
  rm -fr $HOME/.ssh
  sudo cp -r /ssh $HOME/.ssh
  sudo chown -R $USER:$USER $HOME/.ssh
  chmod 600 $HOME/.ssh/id_rsa*
end

if test -d "/work/$PROFILE_NAME"
  echo "setting owner for /work/$PROFILE_NAME"
  sudo chown -R $USER:$USER /work/$PROFILE_NAME
end

if test -n "$DOCKER_GROUP_ID"
  echo "changing docker group to $DOCKER_GROUP_ID"
  sudo groupmod -g $DOCKER_GROUP_ID docker
  sudo adduser $USER docker
end

if test -n "$DOCKER_TOKEN"
  mkdir -p $HOME/.docker
  set CONFIG_FILE $HOME/.docker/config.json
  echo "Using DOCKER_TOKEN"
  printf "\
{
  \"auths\": {
    \"https://index.docker.io/v1/\": {
      \"auth\": \"$DOCKER_TOKEN\"
    }
  }
}" | cat > $CONFIG_FILE
end
sh
