#!/bin/bash


docker pull gregallen/shell
docker run \
  --rm -it \
  --name shell \
  -v shell-dev:/var/work/dev \
  -v shell-history:/home/dev/.local/share/fish \
  -e PROFILE_NAME=dev \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v $HOME/.ssh:/var/work/sshkeys \
  gregallen/shell
