#!/bin/bash

termux-setup-storage
pkg update
pkg install \
  fish \
  tmux \
  python \
  python2 \
  python-dev \
  neovim \
  nodejs \
  fzf \
  silversearcher-ag \
  jq \
  perl \
  pcre \
  clang \
  make \
  less \
  ffmpeg \
  diffutils \
  util-linux \
  gawk \
  curl


pip install awscli neovim awslogs
npm i -g nodemon fx cwl

curl -L https://get.oh-my.fish > $HOME/install && \
  chmod +x $HOME/install && \
  $HOME/install --noninteractive && \
  rm $HOME/install

ln -fs $PWD/vim $HOME/.vim
mkdir -p $HOME/.config/nvim
ln -fs $PWD/vim/vimrc $HOME/.config/nvim/init.vim
ln -fs $PWD/tmux.conf $HOME/.tmux.conf
ln -fs $PWD/gitconfig $HOME/.gitconfig
ln -fs $PWD/npmrc $HOME/.npmrc
rm -rf $HOME/.config/fish
ln -fs $PWD/fish $HOME/.config/fish

mkdir -p $HOME/.vim/bundle
if [[ ! -d "$HOME/.vim/bundle/vundle" ]]; then
  git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/vundle
fi

nvim -es -u $HOME/.vim/bundles.vim +PluginInstall +q

chsh -s fish

#omf install aws
#omf install cbjohnson
#omf install aws-asp
#omf theme cbjohnson
